version: '3.8'

services:
  # MongoDB - Primary database for Legion
  mongodb:
    image: mongo:latest
    container_name: legion-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    environment:
      - MONGO_INITDB_DATABASE=legion
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - legion-network

  # Qdrant - Vector database for semantic search
  qdrant:
    image: qdrant/qdrant:latest
    container_name: legion-qdrant
    ports:
      - "6333:6333"  # HTTP API
      - "6334:6334"  # gRPC API
    volumes:
      - qdrant_storage:/qdrant/storage:z
    environment:
      - QDRANT__SERVICE__GRPC_PORT=6334
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:6333/"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - legion-network

  # Neo4j - Graph database (optional, for future use)
  neo4j:
    image: neo4j:5.13.0
    container_name: legion-neo4j
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    environment:
      - NEO4J_AUTH=neo4j/password123
      - NEO4J_dbms_memory_pagecache_size=512M
      - NEO4J_dbms_memory_heap_initial__size=512M
      - NEO4J_dbms_memory_heap_max__size=2G
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:7474"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - legion-network
    profiles:
      - graph  # Only start if explicitly requested

volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local
  qdrant_storage:
    driver: local
  neo4j_data:
    driver: local
  neo4j_logs:
    driver: local

networks:
  legion-network:
    driver: bridge
