/**
 * TodoResourceProvider - Custom resource provider for Todo app
 * Demonstrates Clean Architecture resource serving
 */

import { ResourceProvider, ResourceResponse, CompositeResourceProvider } from '../../../src/resources/index.js';

export class TodoResourceProvider extends ResourceProvider {
  constructor(defaultProvider) {
    super();
    this.defaultProvider = defaultProvider;
  }

  async getResource(path, req) {
    // Custom resources for todo app
    switch (path) {
      case '/styles.css':
      case '/todo.css':
        return new ResourceResponse({
          type: 'text/css',
          content: this.generateTodoStyles(),
          cache: '5m' // Cache for 5 minutes
        });

      case '/manifest.json':
        return new ResourceResponse({
          type: 'application/json',
          content: JSON.stringify(this.generateManifest(), null, 2),
          cache: '1h'
        });

      default:
        // Fall back to default provider for other resources
        return await this.defaultProvider.getResource(path, req);
    }
  }

  generateTodoStyles() {
    return `
/* Todo App Custom Styles - Generated by Server Actor */
.todo-app {
  max-width: 700px;
  margin: 40px auto;
  padding: 30px;
  background: white;
  border-radius: 12px;
  box-shadow: 0 4px 20px rgba(0,0,0,0.1);
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
}

.todo-header {
  text-align: center;
  margin-bottom: 40px;
  border-bottom: 2px solid #f0f0f0;
  padding-bottom: 20px;
}

.todo-header h1 {
  color: #2c3e50;
  margin: 0 0 10px 0;
  font-size: 2.8em;
  font-weight: 300;
}

.subtitle {
  color: #7f8c8d;
  margin: 0;
  font-size: 1em;
  font-weight: 400;
}

.todo-input-container {
  display: flex;
  gap: 12px;
  margin-bottom: 25px;
}

.todo-input {
  flex: 1;
  padding: 15px 18px;
  border: 2px solid #e1e8ed;
  border-radius: 8px;
  font-size: 16px;
  transition: all 0.3s ease;
  background: #fafafa;
}

.todo-input:focus {
  outline: none;
  border-color: #3498db;
  background: white;
  box-shadow: 0 0 0 3px rgba(52, 152, 219, 0.1);
}

.add-btn {
  padding: 15px 25px;
  background: linear-gradient(135deg, #3498db, #2980b9);
  color: white;
  border: none;
  border-radius: 8px;
  font-size: 16px;
  font-weight: 600;
  cursor: pointer;
  transition: all 0.3s ease;
  box-shadow: 0 2px 8px rgba(52, 152, 219, 0.3);
}

.add-btn:hover {
  background: linear-gradient(135deg, #2980b9, #21618c);
  transform: translateY(-1px);
  box-shadow: 0 4px 12px rgba(52, 152, 219, 0.4);
}

.todo-stats {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 15px 20px;
  background: linear-gradient(135deg, #f8f9fa, #e9ecef);
  border-radius: 8px;
  margin-bottom: 15px;
  border: 1px solid #dee2e6;
}

.stats-text {
  color: #495057;
  font-size: 14px;
  font-weight: 500;
}

.clear-btn {
  padding: 8px 16px;
  background: linear-gradient(135deg, #e74c3c, #c0392b);
  color: white;
  border: none;
  border-radius: 6px;
  font-size: 13px;
  font-weight: 500;
  cursor: pointer;
  transition: all 0.3s ease;
}

.clear-btn:hover {
  background: linear-gradient(135deg, #c0392b, #a93226);
  transform: translateY(-1px);
}

.todo-list {
  list-style: none;
  padding: 0;
  margin: 0;
  border-radius: 8px;
  overflow: hidden;
  border: 1px solid #e1e8ed;
}

.todo-item {
  display: flex;
  align-items: center;
  padding: 18px 20px;
  border-bottom: 1px solid #f0f0f0;
  transition: all 0.2s ease;
  background: white;
}

.todo-item:last-child {
  border-bottom: none;
}

.todo-item:hover {
  background: #f8f9fa;
}

.todo-item.completed {
  background: linear-gradient(135deg, #d5f4e6, #c8e6c9);
}

.todo-item.completed .todo-text {
  text-decoration: line-through;
  color: #6c757d;
}

.todo-checkbox {
  margin-right: 15px;
  width: 22px;
  height: 22px;
  cursor: pointer;
  accent-color: #27ae60;
}

.todo-text {
  flex: 1;
  font-size: 16px;
  color: #2c3e50;
  line-height: 1.4;
}

.delete-btn {
  padding: 8px 12px;
  background: transparent;
  color: #e74c3c;
  border: 2px solid #e74c3c;
  border-radius: 6px;
  font-size: 18px;
  font-weight: bold;
  cursor: pointer;
  opacity: 0.7;
  transition: all 0.3s ease;
  width: 36px;
  height: 36px;
  display: flex;
  align-items: center;
  justify-content: center;
}

.delete-btn:hover {
  background: #e74c3c;
  color: white;
  opacity: 1;
  transform: scale(1.05);
}

.todo-footer {
  text-align: center;
  margin-top: 30px;
  padding-top: 20px;
  border-top: 1px solid #f0f0f0;
  color: #95a5a6;
  font-size: 13px;
}

/* Loading state */
.todo-item.loading {
  opacity: 0.6;
  pointer-events: none;
}

/* Empty state */
.todo-list:empty::after {
  content: "No todos yet. Add one above! 📝";
  display: block;
  text-align: center;
  padding: 40px 20px;
  color: #95a5a6;
  font-style: italic;
  font-size: 16px;
}

/* Responsive design */
@media (max-width: 768px) {
  .todo-app {
    margin: 20px;
    padding: 20px;
    border-radius: 8px;
  }
  
  .todo-input-container {
    flex-direction: column;
  }
  
  .add-btn {
    width: 100%;
  }
  
  .todo-stats {
    flex-direction: column;
    gap: 10px;
    text-align: center;
  }
}

/* Animation for new todos */
@keyframes slideIn {
  from {
    opacity: 0;
    transform: translateX(-20px);
  }
  to {
    opacity: 1;
    transform: translateX(0);
  }
}

.todo-item.new {
  animation: slideIn 0.3s ease-out;
}
`;
  }

  generateManifest() {
    return {
      name: "Legion Todo App",
      short_name: "TodoApp",
      description: "A real-time todo application built with Legion Actor Framework",
      start_url: "/todos",
      display: "standalone",
      theme_color: "#3498db",
      background_color: "#ffffff",
      icons: [
        {
          src: "/favicon.ico",
          sizes: "16x16",
          type: "image/x-icon"
        }
      ]
    };
  }

  async listResources() {
    const customResources = ['/styles.css', '/todo.css', '/manifest.json'];
    const defaultResources = await this.defaultProvider.listResources();
    return [...customResources, ...defaultResources];
  }
}